#!/bin/sh


######################################################
####		 Functions
######################################################

function createMagento {
	# Stop and Remove existing container
	if [ "$(docker ps -a | grep ${CONTAINER_NAME})" ]; then
		docker stop $CONTAINER_NAME &>/dev/null
		docker rm $CONTAINER_NAME &>/dev/null
	fi

	if [ $MVERSION=1 ]; then
		REPO=fsspencer/magento
	else
		REPO=fsspencer/magento2
	fi
	# Create and start container
	echo "\n-------------------------------------"
	echo "Container creation response:"
	echo "-------------------------------------"
	docker run -d --name $CONTAINER_NAME -v $PROJECT_PATH:/var/www/html -p $PORT:80 $REPO
	echo "\n"

	# Get container IP Address
	M2_IPADDRESS=$(docker inspect ${CONTAINER_NAME} | python -c 'import json,sys;obj=json.load(sys.stdin);print obj[0]["NetworkSettings"]["IPAddress"]')
	
}

function createMysql {
	# Stop and Remove existing container
	echo "\n-------------------------------------"
	echo "Mysql container response:"
	echo "-------------------------------------"
	if [ ! "$(docker ps -a | grep mysql)" ]; then
		# Create and start container
		docker stop $(docker ps | grep "3306/tcp")
		docker run -d -ti -e MYSQL_ROOT_PASSWORD="root" -p 3306:3306 --name mysql mysql
	else
		docker start mysql
	fi
	echo "\n"

	# Get container IP Address
	DB_IPADDRESS=$(docker inspect mysql | python -c 'import json,sys;obj=json.load(sys.stdin);print obj[0]["NetworkSettings"]["IPAddress"]')
}


function createDatabase {
	CHECK_IF_EXISTS=$(eval docker exec -ti $CONTAINER_NAME mysql -h $DB_IPADDRESS -uroot -proot -e "USE ${DBNAME};")
	if [ ! -z "$CHECK_IF_EXISTS" ]; then
		echo "Database already exists!"

		read -p "\nDo you wanna drop and re-create ${DBNAME}? [Y/n]: " DROPDB
		if [ "$DROPDB" = "Y" ]; then
			docker exec -ti $CONTAINER_NAME mysql -h $DB_IPADDRESS -uroot -proot -e "DROP DATABASE ${DBNAME};"
		else
			echo "Start the process again with a different DB name"
			exit 1
		fi
		
	fi
	docker exec -ti $CONTAINER_NAME mysql -h $DB_IPADDRESS -uroot -proot -e "CREATE DATABASE ${DBNAME};"
}


function importDatabase {
	docker exec -ti $CONTAINER_NAME mysql -h $DB_IPADDRESS -uroot -proot -e "USE ${DBNAME}; SOURCE ${SQLNAME};"
}

######################################################
####		 User Interaction
######################################################
echo "\n"

if [ -z $(eval command -v docker) ]; then
	"Docker is not installed"
	exit 1
fi

read -p "Magento Version [1 or 2]: " MVERSION
if [ -z "$MVERSION" ]; then
	MVERSION="2"
	echo "Selected Magento 2";
fi

CONTAINER_NAME="magento${MVERSION}"

read -p "Project path [$(eval pwd)]: " PROJECT_PATH
if [ -z "$PROJECT_PATH" ]; then
	PROJECT_PATH=$(eval pwd)
fi

PROJECT_PATH=$(eval echo $PROJECT_PATH | xargs)

read -p "Port [80]: " PORT
if [ -z "$PORT" ]; then
	PORT="80"
fi
docker stop $(docker ps | grep "${PORT}/tcp") &> /dev/null

createMagento

read -p "Create database? [Y/n]: " CREATEDB	
if [ "$CREATEDB" = "Y" ]; then

	read -p "DB Name?: " DBNAME
	if [ -z ${DBNAME} ]; then
	  echo "You need to specify a database name"
	  exit 1
	fi
	createMysql
	createDatabase

	read -p "Import database? [Y/n]: " IMPORTDB
	if [ "$IMPORTDB" = "Y" ]; then

		read -p "SQL Filename (Must be placed in ${PROJECT_PATH})?: " SQLNAME

		if [ ! -f ${PROJECT_PATH}/${SQLNAME} ]; then
	  	  echo "${PROJECT_PATH}/${SQLNAME} File not found!"
	  	  exit 1
		fi

		importDatabase
	else
		IMPORTDB=0
	fi
else
	CREATEDB=0
fi

######################################################
####		 User Output
######################################################

echo "\n-------------------------------------"
echo "Magento IP Address: ${M2_IPADDRESS}"
if [ ! $CREATEDB = 0 ]; then
	echo "MYSQL HOST: ${DB_IPADDRESS}"
	echo "MYSQL USER: root"
	echo "MYSQL PASS: root"
fi
echo "-------------------------------------"